auto-pts enhancements - many auto-pts instances on one machine
codecoup/auto-pts pull request #10
Opened 2021-03-10 12:16 UTC by mkasenberg

Main new features:
- many autoptsserver instances on one Windows machine
- many autoptsclient-zephyr instances on one Windows machine or Linux host
- one autoptsclient_bot on Windows machine

Note: for autoptsclient-zephyr running on Windows, download socat.exe from https://sourceforge.net/projects/unix-utils/files/socat/1.7.3.2/ and add its directory to PATH.

Example runs:

Run many instances of autoptsserver on one Windows machine like:
- in first console:
$ python autoptsserver.py
- in second console:
$ python autoptsserver.py -S 65002
- and more.

Run many autoptsclient-zephyr.py instances on one machine, for Windows it can looks like:
- in third console: (-S 65000 -C 65001 by default)
$ python ./autoptsclient-zephyr.py zephyr-master ~/zephyrproject/zephyr/tests/bluetooth/tester/build/zephyr/zephyr.elf -t COM3 -b nrf52
- in fourth console:
$ python ./autoptsclient-zephyr.py zephyr-master ~/zephyrproject/zephyr/tests/bluetooth/tester/build/zephyr/zephyr.elf -t COM4 -b nrf52 -S 65002 -C 65003
- and more.

On Linux it can looks like:
- in first console:
$ ./autoptsclient-zephyr.py zephyr-master ~/zephyrproject/zephyr/tests/bluetooth/tester/build/zephyr/zephyr.elf -i 192.168.4.2 192.168.4.2 -l 192.168.4.1 192.168.4.1 -t /dev/ttyACM0 -b nrf52
- in second console:
$ ./autoptsclient-zephyr.py zephyr-master ~/zephyrproject/zephyr/tests/bluetooth/tester/build/zephyr/zephyr.elf -i 192.168.4.2 192.168.4.2 -l 192.168.4.1 192.168.4.1 -t /dev/ttyACM1 -b nrf52  -S 65002 -C 65003

Example run of autoptsclient-zephyr for MESH testing:
- for Windows, in third console:
$ python ./autoptsclient-zephyr.py zephyr-master ~/zephyrproject/zephyr/tests/bluetooth/tester/build/zephyr/zephyr.elf -t COM3 -b nrf52 -c MESH -S 65000 65002 -C 65001 65003
- or for Linux host:
$ ./autoptsclient-zephyr.py zephyr-master ~/zephyrproject/zephyr/tests/bluetooth/tester/build/zephyr/zephyr.elf -i 192.168.4.2 192.168.4.2 -l 192.168.4.1 192.168.4.1 -t /dev/ttyACM0 -b nrf52  -c MESH -S 65000 65002 -C 65001 65003

Config for bot has new elements:
z['auto_pts'] = {
    # 'server_ip': ['192.168.3.2', '192.168.3.2'],  # uncomment for Linux host
    # 'local_ip' : ['192.168.3.1', '192.168.3.1'],  # uncomment for Linux host
    'cli_port': [65001, 65003],
    'srv_port': [65000, 65002],
    'project_path': 'C:/Users/Magda/zephyrproject/zephyr',
    'workspace': 'zephyr-master',
    'board': 'nrf52',
    'enable_max_logs': False,
    'retry': 0,
    'bd_addr': '',
}

2021-03-17 08:07 UTC, michal-narajowski commented on autoptsclient_common.py
> +        self.add_argument("-C", "--cl_port", type=int, default=CLIENT_PORT,
cl_port -> cli_port to match srv_port

2021-03-25 20:07 UTC, MariuszSkamra commented on autoptsclient-zephyr.py
> +    if sys.platform == "win32":
you could use the 'have_admin_rights' function from winutils.py

2021-03-26 10:05 UTC, mkasenberg commented on ptsprojects/zephyr/iutctl.py
> +        get_debugger_snr_cmd = 'nrfjprog --com | awk \'/' + tty_file.replace('/', '\\/') + '/ { print $1 }\''
Good point. Moreover, after rebase with Windows workaround commit, I forgot to add the Windows version :)

2021-05-26 11:19 UTC, michal-narajowski requested changes
Looks great! Just a few minor comments.

2021-05-26 11:19 UTC, michal-narajowski commented on bot/zephyr.py
> +            self.ip_addr = args['server_ip']
`if 'server_ip' in args:`

2021-05-26 11:19 UTC, michal-narajowski commented on bot/zephyr.py
> +            if sys.platform == 'win32':
Use localhost as default address regardless of platform.

2021-05-26 11:19 UTC, michal-narajowski commented on bot/common.py
> +            if not devices_in_use.__contains__(srn):
`if not srn in devices_in_use`:

2021-05-26 11:19 UTC, michal-narajowski commented on bot/common.py
> +        raise Exception("No jlinks found")
I would prefer handling errors when they appear instead of catching everything with a try/except.

2021-05-28 14:40 UTC, michal-narajowski approved these changes
LGTM

2021-05-31 09:21 UTC, merged